services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://apidev:3500/jiran-tetangga/v1
      NEXT_PUBLIC_API_KEY: XpnbsxWH6hrnwtbHjr9gTwKFFUj
    ports:
      - 9002:9002
    restart: on-failure
    networks:
      - jiran-tetangga-networks

networks:
  jiran-tetangga-networks:
    external: true
    name: jiran-tetangga-networks